"""empty message

Revision ID: 80486f3d713c
Revises: f32a90e05da6
Create Date: 2016-12-06 17:08:55.736677

"""

# revision identifiers, used by Alembic.
revision = '80486f3d713c'
down_revision = 'f32a90e05da6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('Friday', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('Monday', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('Saturday', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('Sunday', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('Thursday', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('Tuesday', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('Wednesday', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'Wednesday')
    op.drop_column('groups', 'Tuesday')
    op.drop_column('groups', 'Thursday')
    op.drop_column('groups', 'Sunday')
    op.drop_column('groups', 'Saturday')
    op.drop_column('groups', 'Monday')
    op.drop_column('groups', 'Friday')
    # ### end Alembic commands ###
