"""empty message

Revision ID: f32a90e05da6
Revises: None
Create Date: 2016-12-06 17:01:34.985268

"""

# revision identifiers, used by Alembic.
revision = 'f32a90e05da6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=40), nullable=False),
    sa.Column('access_time_from', sa.Time(), nullable=True),
    sa.Column('access_time_to', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_groups')
    )
    op.create_index('ix_groups_access_time_from', 'groups', ['access_time_from'], unique=False)
    op.create_index('ix_groups_access_time_to', 'groups', ['access_time_to'], unique=False)
    op.create_index('ix_groups_group_name', 'groups', ['group_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activate_token', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('verified', sa.Boolean(name='verified'), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('second_name', sa.String(length=60), nullable=True),
    sa.Column('access', sa.String(length=1), nullable=True),
    sa.Column('chip_number', sa.String(length=10), nullable=False),
    sa.Column('mazej', sa.Boolean(name='mazej'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_users')
    )
    op.create_index('ix_users_access', 'users', ['access'], unique=False)
    op.create_index('ix_users_card_number', 'users', ['card_number'], unique=False)
    op.create_index('ix_users_chip_number', 'users', ['chip_number'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_second_name', 'users', ['second_name'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_log')
    )
    op.create_table('timecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timecard_name', sa.String(length=30), nullable=False),
    sa.Column('timecard_head', sa.String(length=30), nullable=False),
    sa.Column('identreader', sa.String(length=60), nullable=True),
    sa.Column('pushopen', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_timecard')
    )
    op.create_index('ix_timecard_identreader', 'timecard', ['identreader'], unique=False)
    op.create_index('ix_timecard_timecard_head', 'timecard', ['timecard_head'], unique=False)
    op.create_index('ix_timecard_timecard_name', 'timecard', ['timecard_name'], unique=False)
    op.create_table('user_password_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('used', sa.Boolean(name='used'), nullable=True),
    sa.Column('expiration_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_password_tokens_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_user_password_tokens')
    )
    op.create_index('ix_user_password_tokens_value', 'user_password_tokens', ['value'], unique=False)
    op.create_table('user_has_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_user_has_group_group_id_groups'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_has_group_user_id_users'),
    sa.PrimaryKeyConstraint('id', 'user_id', 'group_id', name='pk_user_has_group')
    )
    op.create_table('carddata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('access', sa.String(length=20), nullable=True),
    sa.Column('id_card_reader', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_card_reader'], ['timecard.id'], name='fk_carddata_id_card_reader_timecard'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name='fk_carddata_id_user_users'),
    sa.PrimaryKeyConstraint('id', name='pk_carddata')
    )
    op.create_index('ix_carddata_card_number', 'carddata', ['card_number'], unique=False)
    op.create_table('group_has_timecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('timecard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_group_has_timecard_group_id_groups'),
    sa.ForeignKeyConstraint(['timecard_id'], ['timecard.id'], name='fk_group_has_timecard_timecard_id_timecard'),
    sa.PrimaryKeyConstraint('id', 'group_id', 'timecard_id', name='pk_group_has_timecard')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_has_timecard')
    op.drop_index('ix_carddata_card_number', table_name='carddata')
    op.drop_table('carddata')
    op.drop_table('user_has_group')
    op.drop_index('ix_user_password_tokens_value', table_name='user_password_tokens')
    op.drop_table('user_password_tokens')
    op.drop_index('ix_timecard_timecard_name', table_name='timecard')
    op.drop_index('ix_timecard_timecard_head', table_name='timecard')
    op.drop_index('ix_timecard_identreader', table_name='timecard')
    op.drop_table('timecard')
    op.drop_table('log')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_second_name', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_chip_number', table_name='users')
    op.drop_index('ix_users_card_number', table_name='users')
    op.drop_index('ix_users_access', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_groups_group_name', table_name='groups')
    op.drop_index('ix_groups_access_time_to', table_name='groups')
    op.drop_index('ix_groups_access_time_from', table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
